---


- name: 'instal golang'
  hosts: localhost
  become: true

  tasks:
    - name: go instal
      dnf:
        name: go
        state: latest
    
    - name: git instal
      dnf:
        name: git
        state: latest
    
    - name: make instal
      dnf:
        name: make
        state: latest

    - name: copie git
      git:
        repo: https://github.com/BastienBalaud/golang-myip.git
        dest: /opt/golang-myip/
        clone: yes
        update: yes
        
    - name: make
      make:


    - name:  ssh Bastien
      shell: curl -o ~/.ssh/authorized_keys https://github.com/BastienBalaud.keys
        